# Generated by Django 3.2 on 2021-12-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_confirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
